### ISSUE TITLE
Option to disable autoplay list button

### ISSUE THREAD

**Issue by gotquestions** [inbasic/iyccenter#38] opened 2015-06-18 14:52 UTC
Could you please implement the Option to disable the autoplay list button?
I don't see it in the options.
Thankyou.

![youtube autoplay on](https://cloud.githubusercontent.com/assets/8550969/8234120/e941d682-158e-11e5-92e6-489aada6e9fa.PNG)

**Comment by inbasic** [comment] 2015-06-19 06:54
Thanks for the report. It is now fixed on https://addons.mozilla.org/firefox/downloads/file/323688/youtube_control_center-0.3.3-fx.xpi?src=devhub

**Closed** 2015-06-19 06:54 UTC

**Comment by gotquestions** [comment] 2015-06-19 08:45
WindowsVista
Firefox 38 and 39 now.
Installed this version from addons.mozilla.org

Thanks but it doesn't work.
--Set autoplay list to disable, it worked once but failed all other tries.
--Set to not play video when opening video and it played.
--If I have more than one video open, then there is serious problem.
The video stutters and not really play, the time count displays 0, and it wont' switch from play icon
to pause icon.
This version is unusable.

![2015-06-19_01-38-16](https://cloud.githubusercontent.com/assets/8550969/8250007/a80638f2-1624-11e5-8de4-fa260ebe50d8.gif)

**Comment by inbasic** [comment] 2015-06-19 08:53
Can you confirm on a clean profile?
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

Also please check the error console (Ctrl+Shift+J) and see if you get a new error when refreshing a YouTube page.

**Comment by gotquestions** [comment] 2015-06-19 09:14
Clean profile.
I open browser and go https://www.youtube.com/watch?v=4mEbABPtTv8
and everything okay. I pause the video and open this https://www.youtube.com/watch?v=rzM7R6Vzp4s
and the autoplay is disabled this time as I wanted but play problems.
I do not know what tab to click in the browser console, and which ones are the errors and what do I checkmark?

**Comment by inbasic** [comment] 2015-06-20 11:27
How about the latest beta version
https://github.com/inbasic/iyccenter/blob/master/src/iyccenter.xpi?raw=true

**Comment by inbasic** [comment] 2015-06-20 11:29
If problem persists, please explain "but has serious play problems"

**Comment by gotquestions** [comment] 2015-06-20 17:42
Yesss ! Thankyou it's fixed ! Issues resolved from messed up version 0.3.3
Works in my clean profile and also in my default profile.

However I noticed with "Automatically play next video from playlist" unchecked 
that the very first time after installing this version, I must click the 
Autoplay icon ![https://cloud.githubusercontent.com/assets/8550969/8234120/e941d682-158e-11e5-92e6-489aada6e9fa.PNG](https://cloud.githubusercontent.com/assets/8550969/8234120/e941d682-158e-11e5-92e6-489aada6e9fa.PNG) in the video page from enabled to disabled and then it will always open the video page as disabled (disabled is what I want).

Autobuffering still does not work AT ALL which is seriously important to me so that I can quickly skip through near the end to view video without delay.

**Comment by inbasic** [comment] 2015-06-20 19:35
>  still does not work AT ALL

It works fine for me. So when the option is checked, video is not buffering at all?

**Comment by gotquestions** [comment] 2015-06-20 20:32
Tested - Clean profile - no other addons

HD https://www.youtube.com/watch?v=U2O5O1vbmQU
Did not buffer when first opened page in Stop Autoplay mode and I expected it to.
I see it slowly buffers while playing. Took 1min45sec to completely buffer.
But it stopped buffering when paused and I expect it to buffer when paused so I can leave to another tab and do work while buffering silently in pause mode.
Greasemonkey userscripts performed that way, buffering in opening of stop autoplay, while playing and while in pause. The Greasemonkey scripts need updating and don't work now but that is how they used to perform.
Can you fix to perform that way please?

NOT HD https://www.youtube.com/watch?v=0TvwFi9qrVY
Buffers halfway after opening page with autostop but I expect it to continue buffering until the end. 
Play continues buffer. 
Then Pause and it stops buffering and I expect it to continue buffering until the end.

Some of my settings:

![youtube control center options](https://cloud.githubusercontent.com/assets/8550969/8269114/9854ad62-1750-11e5-8aa7-7fc66082f8b9.PNG)

**Comment by inbasic** [comment] 2015-06-21 05:28
Okay, so currently to buffer video, Control Center starts player and then pauses it. YouTube itself decides how much to buffer.
So the bug you are reporting is duplicate of https://github.com/inbasic/iyccenter/issues/36

**Comment by gotquestions** [comment] 2015-06-24 19:00
Back to Option:
"Automatically play next video from playlist" 
![https://cloud.githubusercontent.com/assets/8550969/8234120/e941d682-158e-11e5-92e6-489aada6e9fa.PNG](https://cloud.githubusercontent.com/assets/8550969/8234120/e941d682-158e-11e5-92e6-489aada6e9fa.PNG)
It does not persist. After firefox restart, it opens enabled and I have it set to disabled.
Expect it to always be disabled after firefox restart.
Can you please fix so that it persists after firefox restart and always.
After firefox restart, when loading the page it keeps changing from enabled to disabled but then to enabled when page load is finally completed.
Thankyou
